### ISSUE TITLE
[ET-24] Common 모듈 import 문제 해결

### ISSUE THREAD

**Issue by cnxw4570123** [earlybird-ticket/backend#28]
## 목적

> 모듈 import 문제 해결

## 작업 상세 내용

> Common 모듈 import 과정에서 DB연결이 강제되고, Reactive와 MVC 충돌하는 문제 발생

- DB 연결 강제의 경우 @SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})로 해결

- MVC 충돌 문제는 application.yml에 아래 내용 추가

```yml
spring:
  main:
    allow-bean-definition-overriding: true # WebFluxSecurityConfiguration 빈이 Common과 겹쳐 Override
    web-application-type: reactive # Spring MVC 사용하지 않도록 변경
```

## 참고 사항
- [참고](https://velog.io/@agline/SpringBoot-Failed-to-configure-a-DataSource-url-attribute-is-not-specified-and-no-embedded-datasource-could-be-configured)
